### PR TITLE
RESTful Web API

### PR DESCRIPTION
**Pull request by wwwIgorNet**

### CODE REVIEW

**Comment by rkosmirak** [comment]
Where can I find self check?

**Comment by rkosmirak** [comment]
One of the NFR is “Few of the endpoints should follow the 3rd level.”. Which endpoints satisfy it?

**Comment by wwwIgorNet** [comment]
> Where can I find self check?

Added check.md

**Comment by wwwIgorNet** [comment]
> One of the NFR is “Few of the endpoints should follow the 3rd level.”. Which endpoints satisfy it?

Implemented HATEOAS for Categories GET and Products GET

**Review by rkosmirak — APPROVED** [review]

**Pull request merged**
